PATH:
  DATA: "/content/DATA"
  SAVE: "./models"
MODEL:
  MODEL_NAME: "EfficientNetV2"
  WEIGHT_NAME: "tf_efficientnetv2_m_in21ft1k"
DATA:
  IMG_SIZE: [384, 384]
TRAIN:
  RESUME_TRAIN: False
  EPOCH: 200
  BATCH_SIZE: 8
  VAL_BATCH_SIZE: 1
  LR: 1e-04
  OPTIMIZER: "sam"
  MULTI_CRITERION: False
  CRITERION1: "focal"
  CRITERION2: "ce"
  GAMMA: 2.0
  WEIGHT_DECAY: 1e-06
  SEED: 42
  MIXUP: False
  ALPHA: 0.5
  SCHEDULER: null
  PATIENCE: 15
  RUN_NAME: "EfficientNet_V2_m"
INFERENCE:
  SUBMISSION_NAME: "Model3.csv"
  BATCH_SIZE: 16
